### ISSUE TITLE
Update extension icon image

### ISSUE THREAD

**Issue by TroJan** [GDG-JSS-NOIDA/connect-chrome-extension#1]
Presently the following image is used. 
![icon](https://cloud.githubusercontent.com/assets/4302268/20238053/68bab9ac-a908-11e6-93aa-95d995d285cb.png)

**Comment by deshraj** [comment]
I think you can use http://210.212.85.155/static/images/jss-logo.png

**Comment by TroJan** [comment]
FYI, make sure that the image follow these [guidelines](https://developer.chrome.com/webstore/images#icons)

**Comment by anant-dev** [comment]
hi @TroJan ,  I have made the image according to the mentioned guidelines see the pr #3 
![icon](https://cloud.githubusercontent.com/assets/13196029/20239610/45811cf2-a92a-11e6-989b-c7ed5fe92aa8.png)

**Comment by TroJan** [comment]
@anant-dev : thanks for the help :)
