### ISSUE TITLE
Regrading Updated Chrome Extension App

### ISSUE THREAD

**Issue by ankitjain28may** [GDG-JSS-NOIDA/connect-chrome-extension#5]
Hello @TroJan Sir, I have updated the jss connect chrome extension which i would like to merge with this extension.. Check it out.. [Extension Link](https://github.com/ankitjain28may/JSSConnect-Chrome-Extension)

**Comment by TroJan** [comment]
@ankitjain28may : Please have a look at PR #6. Let me know if it is fine so that I can merge it.

**Comment by ankitjain28may** [comment]
@TroJan Sir, Everything is fine.. but there is a conflict regrading `icon.png`  so please look at it.

**Comment by TroJan** [comment]
@ankitjain28may : Hey, I have updated the current code base with your changes. Have a look at it and for whatever change you want, please create a separate branch and raise a PR.
thanks for your excellent work. will publish the extension soon into chrome extension after all changes(if) are done from your end.

**Comment by ankitjain28may** [comment]
Thanks alot @TroJan sir
